# Site settings
headtitle: Mark Law - Portfolio
title: Think Small
subtitle: Mark Law
email: marklaw@markthelaw.com
url: https://markthelaw.github.io
description: "Mark Law - Software Engineer, Banking Technologist, Android Developer"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Mark Law
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/markthelaw
  - title: github
    url: http://github.com/markthelaw
  - title: linkedin
    url: http://www.linkedin.com/pub/mark-law/3a/5a4/3b2

# Postal address (add as many lines as necessary)
address:
  - line: Somerset
  - line: NJ

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
